### ISSUE TITLE
Error: `The input buffer ran out of bits`

### ISSUE THREAD

**Issue by probablykasper** [charliesome/fdk-aac-rs#1]
I'm trying to integrate this with rodio, but I'm getting an error saying `The input buffer ran out of bits`. I'd love to know what I'm doing wrong here. Thanks, appreciate any help!

This is my code:

#### player.rs
```rust
let file = File::open("/some/path/file.m4a")
  .or(Err("Error opening file"))?;
let buf = BufReader::new(file);
```

#### aac_encoder.rs:
This file is where `BufReader::new` is defined, which is where the error happens (Feel free to ignore the other stuff).
```rust
use std::io::{Read, Seek};
use std::time::Duration;
use rodio::Source;
use fdk_aac::dec::{Decoder, Transport};

pub struct AacDecoder<R>
where
  R: Read + Seek,
{
  reader: R,
  decoder: Decoder,
  current_frame_offset: i32,
  current_frame_data: Vec<i16>,
}

impl<R> AacDecoder<R>
where
  R: Read + Seek,
{
  pub fn new(mut reader: R) -> Result<AacDecoder<R>, R> {
    let mut decoder = Decoder::new(Transport::Adts);

    let dfs = decoder.decoded_frame_size();
    println!("DFS: {}", dfs);

    let mut bufdata_slice = [0; 1024];
    match reader.read(&mut bufdata_slice) {
      Ok(_) => {},
      Err(_) => return Err(reader),
    }
    match decoder.fill(&mut bufdata_slice) {
      Ok(_) => {},
      Err(_) => return Err(reader),
    }

    let mut data_vec: Vec<i16> = vec![];
    let mut data_slice = &mut data_vec[..];
    match decoder.decode_frame(&mut data_slice) {
      Ok(_) => {},
      Err(err) => {
        println!("DecoderError: {}", err);
        return Err(reader)
      },
    }

    Ok(AacDecoder {
      reader: reader,
      decoder: decoder,
      current_frame_offset: 0,
      current_frame_data: data_slice.to_vec(),
    })
  }
  pub fn into_inner(self) -> R {
    self.reader
  }
}

impl<R> Source for AacDecoder<R>
where
  R: Read + Seek,
{
  fn current_frame_len(&self) -> Option<usize> {
    let frame_size: usize = self.decoder.decoded_frame_size();
    Some(frame_size)
  }
  fn channels(&self) -> u16 {
    let num_channels: i32 = self.decoder.stream_info().numChannels;
    num_channels as _
  }
  fn sample_rate(&self) -> u32 {
    let sample_rate: i32 = self.decoder.stream_info().sampleRate;
    sample_rate as _
  }
  fn total_duration(&self) -> Option<Duration> {
    None
  }
}

impl<R> Iterator for AacDecoder<R>
where
  R: Read + Seek,
{
  type Item = i16;

  fn next(&mut self) -> Option<i16> {
    if self.current_frame_offset == self.current_frame_data.len() as i32 {
      // let mut data_vec: Vec<i16> = vec![];
      // let data_slice = &mut data_vec[..];
      let mut data_slice = [0; 1024];
      // let data: &mut [i16];
      let result = self.decoder.decode_frame(&mut data_slice);
      match result {
        Ok(_) => {
          self.current_frame_data = data_slice.to_vec();
          self.current_frame_offset = 0;
        },
        Err(_) => return None,
      }
    }
    let value = self.current_frame_data[self.current_frame_offset as usize];
    self.current_frame_offset += 1;
    return Some(value)
  }
}
```

</details>

**Comment by charliesome** [comment]
Heya! Happy to help out here. You may actually be the first user of this crate other than myself, so apologies for the lack of documentation.

This crate's API is not super Rusty - it's basically a thin but safe wrapper over libfdk-aac and so it is probably a little unclear how to use this crate if you're not already familiar with the libfdk-aac API.

Your main decoding loop must follow this sequence:

* Call the `fill` method to feed encoded AAC data into the decoder's internal buffers. `fill` returns the number of bytes actually read from the byte slice, similar to how [`Write::write`](https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write) works. The decoder will not always read all the data passed to `fill`, so it's important to observe this return value and make sure that the next call to `fill` resumes at the right point.

* Call `decode_frame` to actually decode a frame's worth of samples. It is up to you to make sure the buffer passed to this method is large enough, otherwise you'll drop data. The AAC standard defines a frame as 1024 audio samples per channel, so this buffer's size must be at least 2048 for stereo audio for example.
 
  The `decoded_frame_size` method will tell you how many samples (frame size * channel count) in the pcm buffer are valid, but critically this method will return 0 until the decoder has actually started decoding data, which makes it a bit tricky to know ahead of time how large the buffer passed to `decode_frame` should be ahead of time. In my code, I call `decoder.set_max_output_channels(2)` before `decode_frame`, and always pass a slice of size 2048. AAC supports [at most 8 channels](https://wiki.multimedia.cx/index.php/MPEG-4_Audio#Channel_Configurations), so if you want to be maximally compatible then your buffer should have a size of 8192.

* If `decode_frame` returns a `NOT_ENOUGH_BITS` error, the decoder is telling you that it needs more data before it can produce another decoded frame. Jump back to the start of your decode loop and call `fill` again with more data.

The actual documentation for libfdk-aac is the best place to go for the nitty gritty on this stuff. The decoder PDF doc [is available here](https://github.com/charliesome/fdk-aac-mirror/blob/master/documentation/aacDecoder.pdf) - see section 2.2 Calling Sequence for relevant details.

I hope that helps! Let me know if I can be of any further assistance :)

**Comment by probablykasper** [comment]
@charliesome Thank you, that's incredibly helpful! I really appreciate the detailed explanation.

I'm pretty sure my main problem is that I'm reading from an m4a file and not directly aac, so I would have to read only the audio data from it somehow. Looking into that right now, the [mp4](https://crates.io/crates/mp4) crate seems promising.

Changed the buffer to 8192 and made it `fill()` inside the iterator. With an aac I was able to get _something_ playing, so that's a good start.

**Comment by probablykasper** [comment]
Got .aac files playing now, but got two issues:
1. After it's done playing, I get the error `TRANSPORT_SYNC_ERROR`
2. If my buffer is 8192 and the audio is stereo, it will play the first frame, wait 3 frames, play the second frame, etc.

Aside from that, still gotta figure out reading aac from m4a files.
